"""
run_training.py
===============
End-to-end training orchestrator — single CLI entry point for the full pipeline.

Pipeline stages
---------------
1. Load raw CSV                         (DataProcessor.load)
2. Apply feature engineering            (DataProcessor.apply_feature_engineering)
3. Encode categoricals + train/test split (DataProcessor.encode / .split)
4. Train all 6 model × SMOTE variants   (ModelTrainer.train_all)
   ├─ logistic_regression_no_smote
   ├─ logistic_regression_smote
   ├─ random_forest_no_smote
   ├─ random_forest_smote
   ├─ xgboost_no_smote
   └─ xgboost_smote
5. Select best by test ROC-AUC          (ModelTrainer.train_all)
6. Save artefacts                       (ModelTrainer._save_artefacts)
   ├─ models/best_model.pkl
   ├─ models/model_metadata.json
   └─ models/feature_importance.csv

Dependencies
------------
    pip install xgboost imbalanced-learn scikit-learn numpy pandas

Usage
-----
    # Default run (uses data/churn_dataset.csv)
    python src/run_training.py

    # Custom data path and seed
    python src/run_training.py --data data/churn_dataset.csv --seed 42

    # Custom test size and CV folds
    python src/run_training.py --test-size 0.2 --cv-folds 5
"""

import argparse
import logging
import sys
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

# Ensure the repo root is on sys.path when the script is invoked directly
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from src.data_processing import DataProcessor, DataProcessorConfig
from src.train_model import ModelTrainer


# ---------------------------------------------------------------------------
# Pipeline runner
# ---------------------------------------------------------------------------

def run_pipeline(
    data_path:    Path  = Path("data/churn_dataset.csv"),
    models_dir:   Path  = Path("models"),
    test_size:    float = 0.20,
    cv_folds:     int   = 5,
    random_state: int   = 42,
) -> None:
    """
    Execute the complete training pipeline end-to-end.

    Parameters
    ----------
    data_path    : Path to the raw churn CSV generated by data/generate_data.py.
    models_dir   : Output directory for all saved model artefacts.
    test_size    : Fraction of data reserved for the held-out test set.
    cv_folds     : Number of stratified folds used in cross-validation.
    random_state : Master random seed — controls splits, SMOTE, and all models.
    """
    print("\n" + "=" * 60)
    print("  CUSTOMER CHURN — TRAINING PIPELINE")
    print("=" * 60)

    # ── Stage 1-3 : Data processing ───────────────────────────────────────
    logger.info("Stage 1/2 — Data loading, feature engineering, encoding …")

    config = DataProcessorConfig(
        data_path    = data_path,
        test_size    = test_size,
        random_state = random_state,
    )
    processor = DataProcessor(config)
    X_train, X_test, y_train, y_test = processor.run()
    processor.summary(X_train, X_test, y_train, y_test)

    # ── Stage 4-6 : Training, evaluation, artefact saving ─────────────────
    logger.info(
        "Stage 2/2 — Training 6 variants "
        "(LR, RF, XGBoost) × (no-SMOTE, SMOTE) …"
    )

    trainer = ModelTrainer(
        feature_names = processor.feature_names,
        models_dir    = models_dir,
        random_state  = random_state,
        cv_folds      = cv_folds,
    )
    best = trainer.train_all(X_train, y_train, X_test, y_test)

    # ── Final summary ──────────────────────────────────────────────────────
    print("=" * 60)
    print("  PIPELINE COMPLETE")
    print("=" * 60)
    print(f"  Best model      : {best.run_id}")
    print(f"  SMOTE applied   : {'Yes' if best.smote else 'No'}")
    print(f"  CV  ROC-AUC     : {best.cv_roc_auc:.4f} ± {best.cv_roc_auc_std:.4f}")
    print(f"  Test ROC-AUC    : {best.test_metrics['roc_auc']:.4f}")
    print(f"  Test Precision  : {best.test_metrics['precision']:.4f}")
    print(f"  Test Recall     : {best.test_metrics['recall']:.4f}")
    print(f"  Test F1         : {best.test_metrics['f1']:.4f}")
    print(f"\n  Artefacts saved to  '{models_dir}/'")
    print(f"    ├─ best_model.pkl")
    print(f"    ├─ model_metadata.json")
    print(f"    └─ feature_importance.csv")
    print("=" * 60 + "\n")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Customer Churn Prediction — end-to-end training pipeline",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=Path("data/churn_dataset.csv"),
        help="Path to the raw churn CSV (output of data/generate_data.py)",
    )
    parser.add_argument(
        "--models-dir",
        type=Path,
        default=Path("models"),
        dest="models_dir",
        help="Directory where model artefacts will be saved",
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.20,
        dest="test_size",
        help="Fraction of data held out for testing",
    )
    parser.add_argument(
        "--cv-folds",
        type=int,
        default=5,
        dest="cv_folds",
        help="Number of stratified cross-validation folds",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Master random seed for full reproducibility",
    )
    args = parser.parse_args()

    run_pipeline(
        data_path    = args.data,
        models_dir   = args.models_dir,
        test_size    = args.test_size,
        cv_folds     = args.cv_folds,
        random_state = args.seed,
    )


if __name__ == "__main__":
    main()
